
dev:
	python manage.py runserver

migrations:
	python manage.py makemigrations
# python manage.py makemigrations <app_name> -n <migration_name>
# python manage.py makemigrations guestbook -n create_profile

migrate:
	python manage.py migrate

# admin:admin
superuser:
	python manage.py createsuperuser 

test:
	python manage.py test