# Generated by Django 5.1.2 on 2024-11-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['created_date'], name='guestbook_e_created_5fdd8e_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['guest'], name='guestbook_e_guest_i_295b5c_idx'),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['name'], name='guestbook_g_name_d6cd7e_idx'),
        ),
    ]
