# Generated by Django 5.1.2 on 2024-11-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0003_add_ulid_field_to_entry'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='entry',
            name='guestbook_e_created_5fdd8e_idx',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['created_at'], name='guestbook_e_created_a2d339_idx'),
        ),
    ]
